name: my first workflow
on: 
  workflow_dispatch:
  push:
    branches: 
      - main
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "🎉 The job was triggered by event: ${{ github.event_name }}"
          echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ."
      - name: List files in the repository
        run: |
          echo "The repository ${{ github.repository }} contains the following files:"
          tree
      - uses: actions/checkout@v3.3.0

      - name: List files in the repository
        run: |
          echo "The repository ${{ github.repository }} contains the following files:"
          tree
      - name: Dump GitHub context
        run: echo '${{ toJSON(github)}}'
      - name: Dump GitHub context
        run: echo '${{ toJSON(runner)}}'
      - uses: sofusalbertsen/custom-action@main
        with:
          myInput: Sofus
      - name: run container
        uses: docker://hello-world
      - name: look at the os-release
        run: cat /etc/os-release
      - name: Group of log lines
        run: |
            echo "::group::My title"
            echo "Inside group"
            echo "::endgroup::"
      - run: echo '### This is a part of the summary :rocket:' >>  $GITHUB_STEP_SUMMARY
      - run: echo 'deployed to [github](https://github.com)' >>  $GITHUB_STEP_SUMMARY
      - run: echo "::add-mask::Mona The Octocat"
      - run: echo "Mona The Octocat"
